SET SERVEROUT ON

DROP TABLE FUNCIONARIO_CURSOR

CREATE TABLE FUNCIONARIO_CURSOR (
    CD_FUN NUMBER(10),
    NM_FUN VARCHAR(100),
    SALARIO NUMBER(10,2),
    DT_ADM DATE
);

INSERT INTO FUNCIONARIO_CURSOR (CD_FUN, NM_FUN, SALARIO, DT_ADM) VALUES (1, 'JOÃO', 10000.00, TO_DATE('17/04/2000', 'DD/MM/YYYY'));
INSERT INTO FUNCIONARIO_CURSOR (CD_FUN, NM_FUN, SALARIO, DT_ADM) VALUES (2, 'CLAUDIA', 16000.00, TO_DATE('02/10/1998', 'DD/MM/YYYY'));
INSERT INTO FUNCIONARIO_CURSOR (CD_FUN, NM_FUN, SALARIO, DT_ADM) VALUES (3, 'JOAQUIM', 5500.00, TO_DATE('10/07/2010', 'DD/MM/YYYY'));
INSERT INTO FUNCIONARIO_CURSOR (CD_FUN, NM_FUN, SALARIO, DT_ADM) VALUES (4, 'VALÉRIA', 7300.00, TO_DATE('10/07/2010', 'DD/MM/YYYY'));
INSERT INTO FUNCIONARIO_CURSOR (CD_FUN, NM_FUN, SALARIO, DT_ADM) VALUES (5, 'BRUNO', 8000.00, TO_DATE('11/05/1990', 'DD/MM/YYYY'));

SELECT * FROM FUNCIONARIO_CURSOR;

-- CRIAR UM BLOCO PL/SQL USANDO CURSORES PARA MOSTRAR O NOME DO FUNCIONÁRIO E SEU SALÁRIO

-- CURSOR EXPLÍCITO

DECLARE
    CURSOR FUNCIONARIO_CURSOR IS
        SELECT NM_FUN, SALARIO FROM FUNCIONARIO_CURSOR;
    V_INFOR_FUN FUNCIONARIO_CURSOR%ROWTYPE;

BEGIN
    OPEN FUNCIONARIO_CURSOR;
    LOOP
        FETCH FUNCIONARIO_CURSOR INTO V_INFOR_FUN;
        EXIT WHEN FUNCIONARIO_CURSOR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('NOME: ' || V_INFOR_FUN.NM_FUN || ' | SALARIO: ' || V_INFOR_FUN.SALARIO);
    END LOOP;
    CLOSE FUNCIONARIO_CURSOR;
END;
/
