SET SERVEROUTPUT ON;

DECLARE
    V_CONTADOR NUMBER(2) := 1;
    V_LIMITE NUMBER(2) := 10;

BEGIN
        -- CONDIÇÕES: PRÉ-CONDIÇÃO
        WHILE V_CONTADOR <= V_LIMITE LOOP
        -- INSTRUÇÕES
        DBMS_OUTPUT.PUT_LINE (v_CONTADOR);
        V_CONTADOR := V_CONTADOR + 1;
    END LOOP;
END;