SET SERVEROUTPUT ON;

/* MONTAR TRÊS BLOCOS DE PROGRAMAÇÃO (UTILIZANDO TRÊS LOOPS DIFERENTES) QUE 
REALIZE O PROCESSAMENTO DE UMA TABUADA QUALQUER, POR EXEMPLO A TABUADA DO 
NÚMERO 150*/

DECLARE
    V_TABUADA NUMBER(3) := 150;
    V_INICIO NUMBER(2) := 1;
    V_FIM NUMBER(2) := 10;
    V_RESULTADO NUMBER(4);
    
BEGIN
    -- CONDIÇÕES: PRÉ
    WHILE V_INICIO <= V_FIM LOOP
    -- INSTRUÇÃO
    V_RESULTADO := V_TABUADA * V_INICIO;
    DBMS_OUTPUT.PUT_LINE (V_TABUADA||' X '||V_INICIO||' = '||V_RESULTADO);
    V_INICIO := V_INICIO +1;
    END LOOP;

END;

