/*4. Crie um programa PL/SQL que utilize um cursor explícito para retornar o nome
do departamento com o maior número de funcionários.*/

SET SERVEROUTPUT ON;

DROP TABLE FUNCIONARIO_CURSOR_REV;
CREATE TABLE FUNCIONARIO_CURSOR_REV (
    NOME VARCHAR2(55),
    SALARIO NUMBER(10,2),
    DEPARTAMENTO VARCHAR2(255)
);

INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('BRUNO', 5999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('JOSÉ', 4999.99, 'COMERCIAL');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('MARI', 3999.99, 'JURÍDICO');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('THALITA', 2999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('ISABELE', 3999.99, 'TI');

SELECT * FROM FUNCIONARIO_CURSOR_REV;

COMMIT;

DECLARE

    CURSOR C_FUNCIONARIO_DEPARTAMENTO IS
    SELECT DEPARTAMENTO 
    FROM FUNCIONARIO_CURSOR_REV
    GROUP BY DEPARTAMENTO;
    
    V_DEPARTAMENTO_MAIOR FUNCIONARIO_CURSOR_REV.DEPARTAMENTO%TYPE;
    V_TOTAL_FUNCIONARIOS NUMBER := 0;
    V_TOTAL_FUNCIONARIOS_TEMP NUMBER := 0;

BEGIN

        OPEN C_FUNCIONARIO_DEPARTAMENTO;
    LOOP
        FETCH C_FUNCIONARIO_DEPARTAMENTO INTO V_DEPARTAMENTO_MAIOR;
        EXIT WHEN C_FUNCIONARIO_DEPARTAMENTO%NOTFOUND;

        SELECT COUNT(*) INTO V_TOTAL_FUNCIONARIOS_TEMP
        FROM FUNCIONARIO_CURSOR_REV
        WHERE DEPARTAMENTO = V_DEPARTAMENTO_MAIOR;

        IF V_TOTAL_FUNCIONARIOS_TEMP > V_TOTAL_FUNCIONARIOS THEN
            V_TOTAL_FUNCIONARIOS := V_TOTAL_FUNCIONARIOS_TEMP;
            V_DEPARTAMENTO_MAIOR := V_DEPARTAMENTO_MAIOR;
        END IF;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('O departamento com o maior número de funcionários é o: ' || V_DEPARTAMENTO_MAIOR);

    CLOSE C_FUNCIONARIO_DEPARTAMENTO;
END;
/

