/*6. Crie um programa PL/SQL que utilize um cursor explícito para retornar o nome
do funcionário com o maior salário.*/

DROP TABLE FUNCIONARIO_CURSOR_REV;
CREATE TABLE FUNCIONARIO_CURSOR_REV (
    NOME VARCHAR2(55),
    SALARIO NUMBER(10,2),
    DEPARTAMENTO VARCHAR2(255)
);

INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('BRUNO', 5999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('JOSÉ', 4999.99, 'COMERCIAL');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('MARI', 3999.99, 'JURÍDICO');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('THALITA', 2999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('ISABELE', 3999.99, 'TI');

SELECT * FROM FUNCIONARIO_CURSOR_REV;

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
    CURSOR C_FUNCIONARIO_SAL_MAIOR IS
        SELECT NOME, SALARIO FROM FUNCIONARIO_CURSOR_REV;
    V_NOME_MAIOR_SALARIO FUNCIONARIO_CURSOR_REV.NOME%TYPE;
    V_MAIOR_SALARIO FUNCIONARIO_CURSOR_REV.SALARIO%TYPE := -1; 
    V_NOME_FUNCIONARIO FUNCIONARIO_CURSOR_REV.NOME%TYPE;
    V_SALARIO FUNCIONARIO_CURSOR_REV.SALARIO%TYPE;
BEGIN
    OPEN C_FUNCIONARIO_SAL_MAIOR;
    LOOP
        FETCH C_FUNCIONARIO_SAL_MAIOR INTO V_NOME_FUNCIONARIO, V_SALARIO;
        EXIT WHEN C_FUNCIONARIO_SAL_MAIOR%NOTFOUND;

        IF V_MAIOR_SALARIO < V_SALARIO THEN
            V_MAIOR_SALARIO := V_SALARIO;
            V_NOME_MAIOR_SALARIO := V_NOME_FUNCIONARIO;
        END IF;
    END LOOP;
    CLOSE C_FUNCIONARIO_SAL_MAIOR;
    
    IF V_NOME_MAIOR_SALARIO IS NOT NULL THEN
        DBMS_OUTPUT.PUT_LINE('O funcionário com o maior salário é: ' || V_NOME_MAIOR_SALARIO || ' com salário de ' || V_MAIOR_SALARIO);
    ELSE
        DBMS_OUTPUT.PUT_LINE('Nenhum funcionário encontrado.');
    END IF;
END;
/

