/*15. Escreva um bloco PL/SQL que utilize um cursor implícito para encontrar o
nome do departamento que possui a maior soma de salários.*/

DROP TABLE FUNCIONARIO_CURSOR_REV;
CREATE TABLE FUNCIONARIO_CURSOR_REV (
    NOME VARCHAR2(55),
    SALARIO NUMBER(10,2),
    DEPARTAMENTO VARCHAR2(255)
);

INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('BRUNO', 5999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('JOSÉ', 4999.99, 'COMERCIAL');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('MARI', 3999.99, 'JURÍDICO');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('THALITA', 2999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('ISABELE', 3999.99, 'TI');

SELECT * FROM FUNCIONARIO_CURSOR_REV;

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
    V_DEPARTAMENTO_MAIS_SALARIO FUNCIONARIO_CURSOR_REV.DEPARTAMENTO%TYPE;
    V_SOMA_SALARIOS NUMBER := 0;
    V_SOMA_SALARIOS_MAX NUMBER := 0;
BEGIN
    FOR FUNC IN (SELECT DEPARTAMENTO, SUM(SALARIO) AS TOTAL_SALARIO FROM FUNCIONARIO_CURSOR_REV GROUP BY DEPARTAMENTO) LOOP
        IF FUNC.TOTAL_SALARIO > V_SOMA_SALARIOS_MAX THEN
            V_SOMA_SALARIOS_MAX := FUNC.TOTAL_SALARIO;
            V_DEPARTAMENTO_MAIS_SALARIO := FUNC.DEPARTAMENTO;
        END IF;
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('O departamento com a maior soma de salários é: ' || V_DEPARTAMENTO_MAIS_SALARIO);
END;
/
