/*13. Escreva um bloco PL/SQL que utilize um cursor implícito para calcular o total
de salários pagos pela empresa.*/

DROP TABLE FUNCIONARIO_CURSOR_REV;
CREATE TABLE FUNCIONARIO_CURSOR_REV (
    NOME VARCHAR2(55),
    SALARIO NUMBER(10,2),
    DEPARTAMENTO VARCHAR2(255)
);

INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('BRUNO', 5999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('JOSÉ', 4999.99, 'COMERCIAL');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('MARI', 3999.99, 'JURÍDICO');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('THALITA', 2999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('ISABELE', 3999.99, 'TI');

SELECT * FROM FUNCIONARIO_CURSOR_REV;

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
    V_TOTAL_SALARIOS NUMBER := 0;
BEGIN
    FOR REG_FUNCIONARIO IN (SELECT SALARIO FROM FUNCIONARIO_CURSOR_REV) LOOP
        V_TOTAL_SALARIOS := V_TOTAL_SALARIOS + REG_FUNCIONARIO.SALARIO;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('O total de salários pagos pela empresa é: ' || V_TOTAL_SALARIOS);
END;
/
