/* 1 - ESCREVA UM PROGRAMA PL/SQL QUE USE UM CURSOR IMPLÍCITO PARA PERCORRER UMA
TABELA DE FUNCIONÁRIOS E EXIBIR SEUS NOMES E SALÁRIOS*/

SET SERVEROUTPUT ON;
DROP TABLE FUNCIONARIO_CURSOR_REV;
CREATE TABLE FUNCIONARIO_CURSOR_REV (
    NOME VARCHAR2(55),
    SALARIO NUMBER(10,2)
);

INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('BRUNO', 5999.99);
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('JOSÉ', 4999.99);
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('MARI', 3999.99);

SELECT * FROM FUNCIONARIO_CURSOR_REV;

DECLARE
    V_NOME FUNCIONARIO_CURSOR_REV.NOME%TYPE;
    V_SALARIO FUNCIONARIO_CURSOR_REV.SALARIO%TYPE;
    
BEGIN
    -- ABRE O CURSOR IMPLÍCITO
    FOR REG_FUNCIONARIO IN(SELECT NOME, SALARIO FROM FUNCIONARIO_CURSOR_REV) LOOP
    V_NOME := REG_FUNCIONARIO.NOME;
    V_SALARIO := REG_FUNCIONARIO.SALARIO;
    
    DBMS_OUTPUT.PUT_LINE('Nome: ' || v_nome || ' / Salário: ' || v_salario);
    
    END LOOP;
END;

    