/*12. Crie um programa PL/SQL que utilize um cursor explícito para retornar o
número total de departamentos na empresa.*/

DROP TABLE FUNCIONARIO_CURSOR_REV;
CREATE TABLE FUNCIONARIO_CURSOR_REV (
    NOME VARCHAR2(55),
    SALARIO NUMBER(10,2),
    DEPARTAMENTO VARCHAR2(255)
);

INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('BRUNO', 5999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('JOSÉ', 4999.99, 'COMERCIAL');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('MARI', 3999.99, 'JURÍDICO');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('THALITA', 2999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('ISABELE', 3999.99, 'TI');

SELECT * FROM FUNCIONARIO_CURSOR_REV;

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
    CURSOR C_DEPARTAMENTOS IS
        SELECT DISTINCT DEPARTAMENTO FROM FUNCIONARIO_CURSOR_REV;
    V_TOTAL_DEPARTAMENTOS NUMBER := 0;
    V_DEPARTAMENTO FUNCIONARIO_CURSOR_REV.DEPARTAMENTO%TYPE;
BEGIN
    OPEN C_DEPARTAMENTOS;
    LOOP
        FETCH C_DEPARTAMENTOS INTO V_DEPARTAMENTO;
        EXIT WHEN C_DEPARTAMENTOS%NOTFOUND;
        V_TOTAL_DEPARTAMENTOS := V_TOTAL_DEPARTAMENTOS + 1;
    END LOOP;

    CLOSE C_DEPARTAMENTOS;

    DBMS_OUTPUT.PUT_LINE('O número total de departamentos na empresa é: ' || V_TOTAL_DEPARTAMENTOS);
END;
/
