/*11. Escreva um programa PL/SQL que utilize um cursor implícito para exibir o
nome e o salário de todos os funcionários que têm um salário acima de uma
determinada quantia recebida por parâmetro.*/

DROP TABLE FUNCIONARIO_CURSOR_REV;
CREATE TABLE FUNCIONARIO_CURSOR_REV (
    NOME VARCHAR2(55),
    SALARIO NUMBER(10,2),
    DEPARTAMENTO VARCHAR2(255)
);

INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('BRUNO', 5999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('JOSÉ', 4999.99, 'COMERCIAL');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('MARI', 3999.99, 'JURÍDICO');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('THALITA', 2999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('ISABELE', 3999.99, 'TI');

SELECT * FROM FUNCIONARIO_CURSOR_REV;

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
    V_SALARIO_MINIMO NUMBER := 4000; 
BEGIN
    FOR FUNC IN (SELECT NOME, SALARIO FROM FUNCIONARIO_CURSOR_REV WHERE SALARIO > V_SALARIO_MINIMO) LOOP
        DBMS_OUTPUT.PUT_LINE('Nome: ' || FUNC.NOME || ', Salário: ' || FUNC.SALARIO);
    END LOOP;
END;
/

