/*9. Escreva um bloco PL/SQL que utilize um cursor implícito para encontrar o ID do
departamento que possui a menor quantidade de funcionários.*/

DROP TABLE FUNCIONARIO_CURSOR_REV;
CREATE TABLE FUNCIONARIO_CURSOR_REV (
    NOME VARCHAR2(55),
    SALARIO NUMBER(10,2),
    DEPARTAMENTO VARCHAR2(255)
);

INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('BRUNO', 5999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('JOSÉ', 4999.99, 'COMERCIAL');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('MARI', 3999.99, 'JURÍDICO');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('THALITA', 2999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('ISABELE', 3999.99, 'TI');

SELECT * FROM FUNCIONARIO_CURSOR_REV;

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
    V_DEP_MENOS_FUNC FUNCIONARIO_CURSOR_REV.DEPARTAMENTO%TYPE;
    V_QTD_MINIMA_FUNCIONARIOS NUMBER := NULL; 
    
BEGIN

    FOR DEP IN (SELECT DEPARTAMENTO, COUNT(*) AS TOTAL_FUNC FROM FUNCIONARIO_CURSOR_REV GROUP BY DEPARTAMENTO) LOOP
        IF V_QTD_MINIMA_FUNCIONARIOS IS NULL OR DEP.TOTAL_FUNC < V_QTD_MINIMA_FUNCIONARIOS THEN
            V_QTD_MINIMA_FUNCIONARIOS := DEP.TOTAL_FUNC;
            V_DEP_MENOS_FUNC := DEP.DEPARTAMENTO;
        END IF;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('O departamento com a menor quantidade de funcionários é o: ' || V_DEP_MENOS_FUNC);
END;
/
