/*8. Crie um programa PL/SQL que utilize um cursor explícito para aumentar o
salário de todos os funcionários em um departamento específico.*/

DROP TABLE FUNCIONARIO_CURSOR_REV;
CREATE TABLE FUNCIONARIO_CURSOR_REV (
    NOME VARCHAR2(55),
    SALARIO NUMBER(10,2),
    DEPARTAMENTO VARCHAR2(255)
);

INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('BRUNO', 5999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('JOSÉ', 4999.99, 'COMERCIAL');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('MARI', 3999.99, 'JURÍDICO');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('THALITA', 2999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('ISABELE', 3999.99, 'TI');

SELECT * FROM FUNCIONARIO_CURSOR_REV;

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
    CURSOR C_DEPARTAMENTO_AUMENTO IS
    SELECT NOME, SALARIO FROM FUNCIONARIO_CURSOR_REV
    WHERE DEPARTAMENTO = 'TI';
   
    V_NOME FUNCIONARIO_CURSOR_REV.NOME%TYPE;
    V_SALARIO FUNCIONARIO_CURSOR_REV.SALARIO%TYPE;
    V_AUMENTO_SALARIO NUMBER := 1.10;
     
BEGIN
    OPEN C_DEPARTAMENTO_AUMENTO;
    LOOP
        FETCH C_DEPARTAMENTO_AUMENTO INTO V_NOME, V_SALARIO;
        EXIT WHEN C_DEPARTAMENTO_AUMENTO%NOTFOUND;
        
        V_SALARIO := V_SALARIO * V_AUMENTO_SALARIO;
        
        UPDATE FUNCIONARIO_CURSOR_REV
        SET SALARIO = V_SALARIO
        WHERE NOME = V_NOME;
        
    END LOOP;
    CLOSE C_DEPARTAMENTO_AUMENTO;
    
    DBMS_OUTPUT.PUT_LINE('O salário de todos os funcionários do departamento "TI" foi aumentado em 10%.');
END;
/
















    