/*14. Crie um programa PL/SQL que utilize um cursor explícito para diminuir o
salário de todos os funcionários em um determinado departamento.*/

DROP TABLE FUNCIONARIO_CURSOR_REV;
CREATE TABLE FUNCIONARIO_CURSOR_REV (
    NOME VARCHAR2(55),
    SALARIO NUMBER(10,2),
    DEPARTAMENTO VARCHAR2(255)
);

INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('BRUNO', 5999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('JOSÉ', 4999.99, 'COMERCIAL');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('MARI', 3999.99, 'JURÍDICO');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('THALITA', 2999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('ISABELE', 3999.99, 'TI');

SELECT * FROM FUNCIONARIO_CURSOR_REV;

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
    CURSOR C_FUNCIONARIOS_DEP IS
        SELECT * FROM FUNCIONARIO_CURSOR_REV WHERE DEPARTAMENTO = 'TI';
    V_NOVO_SALARIO NUMBER;
BEGIN
    FOR FUNC IN C_FUNCIONARIOS_DEP LOOP
        V_NOVO_SALARIO := FUNC.SALARIO * 0.9;
        
        UPDATE FUNCIONARIO_CURSOR_REV
        SET SALARIO = V_NOVO_SALARIO
        WHERE NOME = FUNC.NOME;
        
        DBMS_OUTPUT.PUT_LINE('Salário de ' || FUNC.NOME || ' atualizado para ' || V_NOVO_SALARIO);
    END LOOP;
    
    COMMIT;
END;
/
