/*10. Crie um programa PL/SQL que utilize um cursor explícito para retornar o
número total de funcionários em um determinado departamento.*/

DROP TABLE FUNCIONARIO_CURSOR_REV;
CREATE TABLE FUNCIONARIO_CURSOR_REV (
    NOME VARCHAR2(55),
    SALARIO NUMBER(10,2),
    DEPARTAMENTO VARCHAR2(255)
);

INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('BRUNO', 5999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('JOSÉ', 4999.99, 'COMERCIAL');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('MARI', 3999.99, 'JURÍDICO');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('THALITA', 2999.99, 'TI');
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('ISABELE', 3999.99, 'TI');

SELECT * FROM FUNCIONARIO_CURSOR_REV;

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
    V_DEPARTAMENTO FUNCIONARIO_CURSOR_REV.DEPARTAMENTO%TYPE := 'TI';
    CURSOR C_FUNCIONARIOS_DEP IS
        SELECT * FROM FUNCIONARIO_CURSOR_REV WHERE DEPARTAMENTO = V_DEPARTAMENTO;
    V_TOTAL_FUNCIONARIOS NUMBER := 0;
    V_FUNC FUNCIONARIO_CURSOR_REV%ROWTYPE;
BEGIN
    OPEN C_FUNCIONARIOS_DEP;
    LOOP
        FETCH C_FUNCIONARIOS_DEP INTO V_FUNC;
        EXIT WHEN C_FUNCIONARIOS_DEP%NOTFOUND;
        V_TOTAL_FUNCIONARIOS := V_TOTAL_FUNCIONARIOS + 1;
    END LOOP;

    CLOSE C_FUNCIONARIOS_DEP;

    DBMS_OUTPUT.PUT_LINE('O número total de funcionários no departamento ' || V_DEPARTAMENTO || ' é: ' || V_TOTAL_FUNCIONARIOS);
END;
/
