/*3. Escreva um bloco PL/SQL que use um cursor implícito para atualizar os salários
de todos os funcionários em 10%.*/

SET SERVEROUTPUT ON;
DROP TABLE FUNCIONARIO_CURSOR_REV;
CREATE TABLE FUNCIONARIO_CURSOR_REV (
    NOME VARCHAR2(55),
    SALARIO NUMBER(10,2)
);

INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('BRUNO', 5999.99);
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('JOSÉ', 4999.99);
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('MARI', 3999.99);
INSERT INTO FUNCIONARIO_CURSOR_REV VALUES ('THALITA', 2999.99);

SELECT * FROM FUNCIONARIO_CURSOR_REV;

COMMIT;

DECLARE
    V_NOME FUNCIONARIO_CURSOR_REV.NOME%TYPE;
    V_SALARIO FUNCIONARIO_CURSOR_REV.SALARIO%TYPE;
     
BEGIN
    FOR REG_FUNCIONARIO IN (SELECT * FROM FUNCIONARIO_CURSOR_REV) LOOP
        V_NOME := REG_FUNCIONARIO.NOME;
        V_SALARIO := REG_FUNCIONARIO.SALARIO * 1.10;
        
        UPDATE FUNCIONARIO_CURSOR_REV
        SET SALARIO = V_SALARIO
        WHERE NOME = V_NOME;
    END LOOP;
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Salários dos fucnionários atualizados com suncesso.');
END;
/   
    
    
    
    
    
    