/*
MEU PRIMEIRO PROGRAMA EM PL / SQL
*/
SET SERVEROUTPUT ON;
DECLARE

V_ALUNO2024 VARCHAR2(100);

BEGIN -- OBRIGATÓRIO
    SELECT NOME
        INTO V_ALUNO2024
        FROM ALUNO2024
        WHERE RM = 99097;
    
    dbms_output.put_line ('O NOME DO ALUNO É ' || V_ALUNO2024);

END; -- OBRIGATÓRIO