/* UM PACOTE É UM OBJETO DE ESQUEMA QUE AGRUPA TIPOS PL/SQL LOGICAMENTE
RELACIONADOS, VARIAVEIS E SUBPROGRAMAS. OS PACOTES GERALMENTE POSSUEM DUAS
PARTES, UMA ESPECIFICAÇÃO E UM CORPO

- CREATE [OR REPLACE] PACKAGE - PERMITE CRIAR A ESPECIFICAÇÃO DO PACOTE QUE 
SÃO ARMAZENADAS EM UM BANCO
- CREATE [OR REPLACE] PACKAGE BODY - PERMITE CRIAR UM BLOCO DE ÓDIGO ARMAZENANDO
NO BANCO QUE CONTEM A IMPLEMENTAÇÃO DAS ESPECIFICAÇÕES DO PACOTE.

ESPECIFICAÇÃO DO PACOTE CONTEM DECLARAÇÕES PUBLICAS. OS ITENS DECLARADOS SÃO
ACESSIVEL DE QUALQUER LUGAR NO CORPO DO PACOTE E PARA QUAISQUER OUTROS SUBPROGRMAS
NO MESMO ESQUEMA.*/

CREATE OR REPLACE PACKAGE PKG_ALUNO AS
-- GET NOME COMPLETO DO ALUNO
FUNCTION GET_NOME(P_RM NUMBER)
RETURN VARCHAR2;
-- GET RM DO ALUNO
FUNCTION GET_RM(P_NOME VARCHAR2)
RETURN NUMBER;
END PKG_ALUNO;
/

