/*
CRIAR UM BLOCO PL-SQL PARA CALCULAR O VALOR EM REAIS DE 45 DOLARES, 
SENDO QUE O VALOR DO CAMBIO A SER CONSIDERADO É DE R$4,97
*/

SET SERVEROUTPUT ON;

DECLARE
    V_VALOR_DOLAR CONSTANT NUMBER := 45;
    V_CAMBIO_REAIS CONSTANT NUMBER := 4.97;
    V_VALOR_EM_REAIS NUMBER;
BEGIN
    -- CALCULAR VALOR EM REAIS
    V_VALOR_EM_REAIS := V_VALOR_DOLAR * V_VALOR_EM_REAIS;

    -- RESULTADO
    DBMS_OUTPUT.PUT_LINE('O valor em reais de $' || V_VALOR_DOLAR || ' é R$' || V_VALOR_EM_REAIS);
END;

