SET SERVEROUTPUT ON;

DECLARE
    V_SALARIO_ATUAL NUMBER(10,2) := 1412.00;
    V_NOVO_SALARIO NUMBER(10,2);
BEGIN
    V_NOVO_SALARIO := V_SALARIO_ATUAL * 1.25;
    
    -- EXIBIR NOVO SALARIO
    DBMS_OUTPUT.PUT_LINE('O novo salário mínimo será: R$' || V_NOVO_SALARIO);
END;
