DROP TABLE ALUNOFIAP2024;
CREATE TABLE ALUNOFIAP2024(
    RM NUMBER(10),
    NOME VARCHAR(50),
    SOBRENOME VARCHAR(50),
    CONSTRAINT ALUNOFIAP2024_PK PRIMARY KEY (RM)
);

SELECT * FROM ALUNOFIAP2024;
SELECT * FROM ALUNOFIAP2024 WHERE RM = &DIGITE_RM_DO_ALUNO;
SELECT * FROM ALUNOFIAP2024 WHERE NOME = '&DIGITE_O_NOME_DO_ALUNO';
-- SELECT * FROM ALUNOFIAP2024 WHERE NOME = &DIGITE_O_NOME_DO_ALUNO; [NECESSÁRIO UTILIZAR ASPAS QUANDO INPUTAR O DADO]

INSERT INTO ALUNOFIAP2024 (RM,NOME,SOBRENOME) VALUES (99097,'Bruno','Ciccio');
INSERT INTO ALUNOFIAP2024 (RM,NOME,SOBRENOME) VALUES (99098,'José','Duarte');
INSERT INTO ALUNOFIAP2024 (RM,NOME,SOBRENOME) VALUES (99099,'Marina','Cucco');

COMMIT;