/*
CRIAR UM BLOCO PL-SQL PARA CALCULAR O VALOR DAS PARCELAS DA COMPRA DE UM CARRO,
NAS SEGUINTES CONDIÇÕES:
1 - PARCELAS PARA AQUISIÇÃO EM 10 PAGAMENTOS
2 - O VALOR DA COMPRA DEVERÁ SER INFORMADO EM TEMPO DE EXECUÇÃO
3 - O VALOR TOTAL DOS JUROS É DE 3% E DEVERÁ SER APLICADO SOBRE O MONTANTE FINANCIADO
4 - NO FINAL INFORMAR O VALOR DE CADA PARCELA.
5 - VALOR DE ENTRADA DO CARRO = 50 MIL REAIS
*/

SET SERVEROUTPUT ON;

DECLARE
    V_QTD_PARCELA NUMBER(2) := &QTD_PARCELA;
    V_VALOR_CARRO NUMBER(10,2) := &VALOR_CARRO;
    V_VALOR_JUROS NUMBER(10,2) := 1.03; -- 3%
    V_VALOR_PRESTACAO NUMBER(10,2);

BEGIN
    V_VALOR_PRESTACAO := (V_VALOR_CARRO * V_VALOR_JUROS) / V_QTD_PARCELA;
    dbms_output.put_line('Valor do carro: ' || V_VALOR_CARRO);
    dbms_output.put_line('Valor da prestação em 10 parcelas: ' || V_VALOR_PRESTACAO);

END;


