-- Especificação (Specification)
CREATE OR REPLACE PACKAGE PKG_PACOTE IS
    PROCEDURE CALCULA_REAJUSTE(P_SAL_ATUAL IN NUMBER);
END PKG_PACOTE;
/

-- Corpo (Body)
CREATE OR REPLACE PACKAGE BODY PKG_PACOTE IS
    PROCEDURE CALCULA_REAJUSTE(P_SAL_ATUAL IN NUMBER) IS
        V_SAL_REAJ NUMBER(7,2);
    BEGIN
        V_SAL_REAJ := P_SAL_ATUAL * 1.25;
        DBMS_OUTPUT.PUT_LINE('SALÁRIO ATUAL - R$: ' || P_SAL_ATUAL);
        DBMS_OUTPUT.PUT_LINE('SALÁRIO REAJUSTADO - R$: ' || V_SAL_REAJ);
    END CALCULA_REAJUSTE;
END PKG_PACOTE;
/
