SET SERVEROUTPUT ON

EXECUTE PKG_PACOTE.CALCULA_REAJUSTE(1500);

ALTER PACKAGE PKG_PACOTE COMPILE;
ALTER PACKAGE PKG_PACOTE COMPILE BODY;

DROP PACKAGE PKG_PACOTE;

-- PRIVILÉGIO DE ACESSO (PARA QUALQUER PESSOA ACESSAR, CASO SEJA PARA UMA PESSOA
-- ESPECÍFICA ACESSAR, TROCAR PUBLIC PELO NOME ESPECÍFICO
GRANT EXECUTE ON PKG_PACKAGE TO PUBLIC;