/* EXERCÍCIO 2:
CRIAR NO PACOTE CALCULADORA UMA FUNÇÃO PARA CALCULAR O VALOR EM REAIS DE
45 DOLARES, SENDO QUE O VALOR DO CAMBIO A SER CONSIDERADO É DE 5,04*/

CREATE OR REPLACE PACKAGE PKG_CALCULADORA IS
    PROCEDURE CALCULA_NOVO_SAL_MIN;
    FUNCTION CONVERTE_DOLAR_PARA_REAL RETURN NUMBER;
END PKG_CALCULADORA;
/

CREATE OR REPLACE PACKAGE BODY PKG_CALCULADORA IS

    PROCEDURE CALCULA_NOVO_SAL_MIN IS
        V_SAL_ATUAL NUMBER := 1320.00;
        V_SAL_REAJ NUMBER(7,2);
    BEGIN
        V_SAL_REAJ := V_SAL_ATUAL * 1.25;
        DBMS_OUTPUT.PUT_LINE('SALÁRIO MÍNIMO ATUAL - R$: ' || V_SAL_ATUAL);
        DBMS_OUTPUT.PUT_LINE('SALÁRIO MÍNIMO REAJUSTADO - R$: ' || V_SAL_REAJ);
    END CALCULA_NOVO_SAL_MIN;

    FUNCTION CONVERTE_DOLAR_PARA_REAL RETURN NUMBER IS
        V_VALOR_DOLAR NUMBER := 45;
        V_CAMBIO NUMBER := 5.04;
        V_VALOR_EM_REAIS NUMBER;
    BEGIN
        V_VALOR_EM_REAIS := V_VALOR_DOLAR * V_CAMBIO;
        RETURN V_VALOR_EM_REAIS;
    END CONVERTE_DOLAR_PARA_REAL;

END PKG_CALCULADORA;
/

