/*2) CRIAR UM BLOCO QUE RECEBERÁ UM RM, UM NOME E QUATRO NOTAS CONFORME A SEQUENCIA:
(RM,NOME,A1,A2,A3,A4), MÍNIMO DE DADOS: 2 LINHAS PARA APROVADO E UMA PARA REPROVADO
A PARTIR CRIAR UM BLOCO PL/SQL USANDO CURSORES PARA PROCESSAR O CÁLCULO DE MÉDIA
SOMANDO O MAIOR VALOR ENTRE A1 E A2 ÀS NOTAS A3 E A4 E DIVIDINDO O VALOR OBTIDO
POR TRÊS (ACHANDO A MÉDIA)
SE A MÉDIA FOR MENOR QUE 6(SEIS) O ALUNO ESTARÁ REPROVADO E SE A MÉDIA FOR IGUAL 
OU SUPERIOR A 6(SEIS) O ALUNO ESTARÁ APROVADO.
O BLOCO DEVERÁ INSERIR OS VALORES ACIMA NUMA TABELA DENOMINADA ALUNO COM AS SEGUINTES
COLUNAS RM,NOME,A1,A2,A3,A4,MEDIA,RESULTADO.*/

DROP TABLE ALUNO_CURSOR_CP;
CREATE TABLE ALUNO_CURSOR_CP(
    RM NUMBER(10) PRIMARY KEY,
    NOME VARCHAR2(255),
    A1 NUMBER(4,2),
    A2 NUMBER(4,2),
    A3 NUMBER(4,2),
    A4 NUMBER(4,2),
    MEDIA NUMBER(4,2),
    RESULTADO VARCHAR2(255)
);

INSERT INTO ALUNO_CURSOR_CP VALUES(99097,'BRUNO',9.5,8.7,9.9,10,NULL,NULL);
INSERT INTO ALUNO_CURSOR_CP VALUES(99098,'JOSÉ',9.3,6.6,9.8,9.8,NULL,NULL);
INSERT INTO ALUNO_CURSOR_CP VALUES(99099,'MARINA',9.5,5.7,9.2,10,NULL,NULL);
INSERT INTO ALUNO_CURSOR_CP VALUES(99100,'THALITA',4.5,6.7,3.9,5.1,NULL,NULL);
INSERT INTO ALUNO_CURSOR_CP VALUES(99101,'ISABELLE',6.5,6,4.3,4.1,NULL,NULL);

SELECT * FROM ALUNO_CURSOR_CP;

DECLARE
    v_media NUMBER(4,2);
BEGIN
    -- Declaração de cursor implícito
    FOR aluno IN (SELECT * FROM ALUNO_CURSOR_CP) LOOP
        -- Calcular a média considerando as condições especificadas
        v_media := (GREATEST(aluno.A1, aluno.A2) + aluno.A3 + aluno.A4) / 3;
        
        -- Determinar se o aluno foi aprovado ou reprovado
        IF v_media >= 6 THEN
            aluno.MEDIA := v_media;
            aluno.RESULTADO := 'APROVADO';
        ELSE
            aluno.MEDIA := v_media;
            aluno.RESULTADO := 'REPROVADO';
        END IF;
        
        -- Atualizar a tabela ALUNO_CURSOR_CP com os valores calculados
        UPDATE ALUNO_CURSOR_CP
        SET MEDIA = aluno.MEDIA,
            RESULTADO = aluno.RESULTADO
        WHERE RM = aluno.RM;
        
        COMMIT; -- Confirmar a transação
    END LOOP;
END;
/
