/* 1) Criar um bloco PL/11111sql (usando cursor) para atualizar a tabela abaixo,
conforme segue:
produtos categoria A deverão ser reajustados em 5%
produtos categoria B deverão ser reajustados em 10%
produtos categoria C deverão ser reajustados em 15%
CREATE TABLE PRODUTO_CP (
CODIGO NUMBER(4),
CATEGORIA CHAR(1),
VALOR NUMBER(4, 2));
INSERT INTO PRODUTO_CP VALUES (1001,'A',7.55);
INSERT INTO PRODUTO_CP VALUES (1002,'B',5.95);
INSERT INTO PRODUTO_CP VALUES (1003,'C',3.45);*/

SET SERVEROUT ON

DROP TABLE PRODUTO_CURSOR;
CREATE TABLE PRODUTO_CURSOR (
    CODIGO NUMBER(4),
    CATEGORIA CHAR(1),
    VALOR NUMBER(4,2)
);

INSERT INTO PRODUTO_CURSOR VALUES (1001,'A',7.55);
INSERT INTO PRODUTO_CURSOR VALUES (1002,'B',5.95);
INSERT INTO PRODUTO_CURSOR VALUES (1003,'C',3.45);

SELECT * FROM PRODUTO_CURSOR;

-- CURSOR EXPLÍCITO
DECLARE
    V_VALOR NUMBER(10,2);
    CURSOR PRODUTO_CURSOR IS
        SELECT CODIGO, CATEGORIA, VALOR FROM PRODUTO_CURSOR;
    V_INFO_PRODUTO_CURSOR PRODUTO_CURSOR%ROWTYPE;

BEGIN
        OPEN PRODUTO_CURSOR;
    LOOP
        FETCH PRODUTO_CURSOR INTO V_INFO_PRODUTO_CURSOR;
        EXIT WHEN PRODUTO_CURSOR%NOTFOUND;
        -- LÓGICA
        IF V_INFO_PRODUTO_CURSOR.CATEGORIA = 'A' THEN
           V_VALOR := V_INFO_PRODUTO_CURSOR.VALOR * 1.05;
           DBMS_OUTPUT.PUT_LINE('Produto ' || V_INFO_PRODUTO_CURSOR.CODIGO || ' da categoria A foi reajustado em 5%. Novo valor: ' ||  V_INFO_PRODUTO_CURSOR.VALOR);
        ELSIF V_INFO_PRODUTO_CURSOR.CATEGORIA = 'B' THEN
           V_VALOR := V_INFO_PRODUTO_CURSOR.VALOR * 1.10;
           DBMS_OUTPUT.PUT_LINE('Produto ' || V_INFO_PRODUTO_CURSOR.CODIGO || ' da categoria B foi reajustado em 10%. Novo valor: ' || V_INFO_PRODUTO_CURSOR.VALOR);
        ELSE 
            V_VALOR := V_INFO_PRODUTO_CURSOR.VALOR * 1.15;
            DBMS_OUTPUT.PUT_LINE('Produto ' || V_INFO_PRODUTO_CURSOR.CODIGO || ' da categoria C foi reajustado em 15%. Novo valor: ' || V_INFO_PRODUTO_CURSOR.VALOR);
        END IF;
        -- ATUALIZAR A TABELA   
        UPDATE PRODUTO_CURSOR
        SET VALOR = V_VALOR
        WHERE CODIGO = V_INFO_PRODUTO_CURSOR.CODIGO;
               
    END LOOP;
    CLOSE PRODUTO_CURSOR;
    
    COMMIT; -- CONFIRMAR AS ALTERAÇÕES FEITAS

END;
/