SET SERVEROUT ON

DROP TABLE PRODUTO_CURSOR;
CREATE TABLE PRODUTO_CURSOR (
    CODIGO NUMBER(4),
    CATEGORIA CHAR(1),
    VALOR NUMBER(4,2)
);

INSERT INTO PRODUTO_CURSOR VALUES (1001,'A',7.55);
INSERT INTO PRODUTO_CURSOR VALUES (1002,'B',5.95);
INSERT INTO PRODUTO_CURSOR VALUES (1003,'C',3.45);

SELECT * FROM PRODUTO_CURSOR;

-- CURSOR IMPLÍCITO
DECLARE
    CURSOR C_REAJUSTE IS
        SELECT * FROM PRODUTO_CURSOR;
 
BEGIN
    FOR REGISTRO IN C_REAJUSTE LOOP
        IF REGISTRO.CATEGORIA = 'A' THEN
        UPDATE PRODUTO_CURSOR SET VALOR = VALOR * 1.05 WHERE CODIGO = REGISTRO.CODIGO;
        ELSIF REGISTRO.CATEGORIA = 'B' THEN
        UPDATE PRODUTO_CURSOR SET VALOR = VALOR * 1.10 WHERE CODIGO = REGISTRO.CODIGO; 
        ELSE 
        UPDATE PRODUTO_CURSOR SET VALOR = VALOR * 1.15 WHERE CODIGO = REGISTRO.CODIGO;
    END IF;   --AQUI VC ENCERRA O USO DO IF
    END LOOP; --AQUI VC ENCERRA O USO DO LOOP
END;
 
