SET SERVEROUTPUT ON;

/* EXERCICIO PARA ESTRUTURA DE REPETIÇÃO
CRIAR UM BLOCO PL/SQL PARA IMPRIMIR NA TELA OS NÚMEROS DE FORMA CRESCENTE,
O BLOCO DEVERÁ RECEBER UM DADO NUMÉRICO QUE REPRESENTA A QUANTIDADE DE NÚMEROS
A SEREM IMPRESSOS */

DECLARE
    V_CONTADOR NUMBER(10) := 1;
    V_FIM V_CONTADOR%TYPE := &DIGITE_UM_NUMERO;

BEGIN    
    LOOP
        -- INSTRUÇÕES
        DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
        V_CONTADOR := V_CONTADOR +1;
        EXIT WHEN (V_CONTADOR > V_FIM); -- CONDIÇÃO
    END LOOP;

END;