SET SERVEROUTPUT ON;

/* CONSTRUA UMA TABUADA */

DECLARE
    V_CONTADOR NUMBER(10) := 1;
    V_TABUADA V_CONTADOR%TYPE := &DIGITE_O_NUMERO_DA_TABUADA;
    V_FIM V_CONTADOR%TYPE := 10;
    V_RESULTADO V_CONTADOR%TYPE;

BEGIN    
    LOOP
        -- INSTRUÇÕES
        V_RESULTADO := V_TABUADA * V_CONTADOR;
        DBMS_OUTPUT.PUT_LINE(V_TABUADA || ' X ' || V_CONTADOR || ' = ' || V_RESULTADO);
        V_CONTADOR := V_CONTADOR +1;
        EXIT WHEN (V_CONTADOR > V_FIM); -- CONDIÇÃO
    END LOOP;

END;