/* CRIAR UM BLOCO PL/SQL PARA IPRIMIR NA TELA OS NOMES 
DOS ALUNOS DA TABELA ALUNO*/

DROP TABLE ALUNOLOOP;
CREATE TABLE ALUNOLOOP ( 
    NOME VARCHAR2(50),
    RM NUMBER(10)
);

INSERT INTO ALUNOLOOP (NOME,RM) VALUES ('Bruno', 1);
INSERT INTO ALUNOLOOP (NOME,RM) VALUES ('José', 2);
INSERT INTO ALUNOLOOP (NOME,RM) VALUES ('Marina', 3);
INSERT INTO ALUNOLOOP (NOME,RM) VALUES ('Isabelle', 4);
INSERT INTO ALUNOLOOP (NOME,RM) VALUES ('Thalita', 5);

SELECT * FROM ALUNOLOOP;

SET SERVEROUTPUT ON;

DECLARE
    V_RM NUMBER(10) := 1;
    V_NOME VARCHAR2(50);
    V_FIM V_RM%TYPE := 5;
    
BEGIN    
    LOOP
        -- INSTRUÇÕES
        SELECT NOME INTO V_NOME FROM ALUNOLOOP WHERE RM LIKE V_RM || '%';
        DBMS_OUTPUT.PUT_LINE(V_NOME);
        V_RM := V_RM +1;
        EXIT WHEN (V_RM > V_FIM); -- CONDIÇÃO
    END LOOP;

END;

