/* 2) Criar uma PROCEDURE PARA CALCULAR O VALOR DE UM
NOVO AUMENTO DOS FUNCIONÁRIOS QUE GANHAM MENOS
QUE UM SALÁRIO-MÍNIMO, APÓS O AUMENTO DO SALÁRIO
MINIMO, RECEBENDO O SALÁRIO MINIMO DA PROCEDURE
ANTERIOR. */

DROP TABLE FUNCIONARIOS;
CREATE TABLE FUNCIONARIOS_PROCEDURE (
    ID NUMBER PRIMARY KEY,
    SALARIO_ATUAL NUMBER
);

INSERT INTO FUNCIONARIOS_PROCEDURE (ID, SALARIO_ATUAL) VALUES (1, 1000);
INSERT INTO FUNCIONARIOS_PROCEDURE (ID, SALARIO_ATUAL) VALUES (2, 1200);
INSERT INTO FUNCIONARIOS_PROCEDURE (ID, SALARIO_ATUAL) VALUES (3, 1400);
INSERT INTO FUNCIONARIOS_PROCEDURE (ID, SALARIO_ATUAL) VALUES (4, 1800);
INSERT INTO FUNCIONARIOS_PROCEDURE (ID, SALARIO_ATUAL) VALUES (5, 2000);

SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE ATUALIZAR_SALARIOS_FUNCIONARIOS (
    NOVO_SALARIO_MINIMO IN NUMBER
) AS
BEGIN
    -- ATUALIZAR SALARIO DOS FUNCIONARIOS QUE GANHAM MENOS QUE UM SAL MINIMO
    UPDATE FUNCIONARIOS_PROCEDURE
    SET SALARIO_ATUAL = NOVO_SALARIO_MINIMO
    WHERE SALARIO_ATUAL < NOVO_SALARIO_MINIMO;
    
    -- QUANTIDADE DE FUNCIONARIOS QUE RECEBERAM O AUMENTO
    DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT || ' FUNCIONARIOS FORAM ATUALIZADOS PARA O NOVO SALARIO MINIMO DE' || TO_CHAR(NOVO_SALARIO_MINIMO, '9999.00'));
END;
/

DECLARE
    SALARIO_ATUAL NUMBER := 1412.00;
    NOVO_SALARIO_MINIMO NUMBER;
BEGIN
    -- PROCEDURE
    ATUALIZAR_SALARIO_MINIMO(SALARIO_ATUAL, NOVO_SALARIO_MINIMO);
    
    -- EXIBIR O NOVO SALÁRIO MÍNIMO
    DBMS_OUTPUT.PUT_LINE('O ATUAL SALARIO MINIMO É DE' || TO_CHAR(SALARIO_ATUAL, '9999.00') ||
    ', COM O AUMENTO DE 25% O NOVO SALARIO MINIMO PASSA A SER' || TO_CHAR(NOVO_SALARIO_MINIMO, '9999.00'));
    
    -- CHAMAR A PROCEDURE PARA ATUALIZAR OS SALARIOS DOS FUNCIONARIOS
    ATUALIZAR_SALARIOS_FUNCIONARIOS(NOVO_SALARIO_MINIMO);
EXCEPTION
    WHEN OTHERS THEN
        -- CAPTURAR ERROS
        DBMS_OUTPUT.PUT_LINE('ERRO: ' || SQLERRM);
END;
/

