/*1) Criar uma PROCEDURE PARA ALTERAR O VALOR DO NOVO
SALÁRIO-MÍNIMO, QUE É DE 25% DO ATUAL, SENDO QUE
DEVERÁ INFORMAR O ATUAL SALÁRIO NO PARAMETRO,
PASSANDO UM PARAMETRO DE SAÍDA DO NOVO SALÁRIO
MINIMO. */

SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE ATUALIZAR_SALARIO_MINIMO (
    SALARIO_ATUAL IN NUMBER,
    NOVO_SALARIO_MINIMO OUT NUMBER
) AS
BEGIN
    -- CALCULAR O SALÁRIO ACRESCENTANDO 25%
    NOVO_SALARIO_MINIMO := SALARIO_ATUAL * 1.25;
END;
/

DECLARE
    SALARIO_ATUAL NUMBER := 1412.00;
    NOVO_SALARIO_MINIMO NUMBER;
BEGIN
    -- PROCEDURE
    ATUALIZAR_SALARIO_MINIMO(SALARIO_ATUAL, NOVO_SALARIO_MINIMO);
    -- EXIBIR O NOVO SALÁRIO MÍNIMO
    DBMS_OUTPUT.PUT_LINE('O ATUAL SALARIO MINIMO É DE' || TO_CHAR(SALARIO_ATUAL, '9999.00') ||
    ', COM O AUMENTO DE 25% O NOVO SALARIO MINIMO PASSA A SER' || TO_CHAR(NOVO_SALARIO_MINIMO, '9999.00'));
EXCEPTION
    WHEN OTHERS THEN
        -- CAPTURAR ERROS
        DBMS_OUTPUT.PUT_LINE('ERRO: ' || SQLERRM);
END;
/
