/*3) Criar uma PROCEDURE PARA ATUALIZAR O NOME DO
FORNECEDOR NA TABELA FORNECEDOR PASSANDO UM
PARAMETRO NOME, UTILIZANDO CURSORES, LOOP E
%ROWTYPE.*/

DROP TABLE FORNECEDOR_PROCEDURE;
CREATE TABLE FORNECEDOR_PROCEDURE (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    ENDERECO VARCHAR2(100)
);

INSERT INTO FORNECEDOR_PROCEDURE (ID, NOME, ENDERECO) VALUES (1, 'Fornecedor A', 'Endereço A');
INSERT INTO FORNECEDOR_PROCEDURE (ID, NOME, ENDERECO) VALUES (2, 'Fornecedor B', 'Endereço B');
INSERT INTO FORNECEDOR_PROCEDURE (ID, NOME, ENDERECO) VALUES (3, 'Fornecedor C', 'Endereço C');

SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE ATUALIZAR_NOME_FORNECEDOR (
    P_ID IN NUMBER,
    NOVO_NOME IN VARCHAR2
) AS
BEGIN
    UPDATE FORNECEDOR_PROCEDURE
    SET NOME = NOVO_NOME
    WHERE ID = P_ID;
    
    DBMS_OUTPUT.PUT_LINE('Nome do fornecedor com ID ' || P_ID || ' atualizado para ' || NOVO_NOME);
END;
/

BEGIN
    ATUALIZAR_NOME_FORNECEDOR(1, 'FORNECEDOR ABC');
END;
/
