/*Pré-requisito para desenvolver os exercícios de 8 à 10
Criar uma tabela com nome Fornecedor com as colunas id_fornecedor,
nome, endereco, valor_vendas, valor_comissões, valor_juros e valor_lucro.
Incluir 5 registros com os campos comissões, juros e lucro vazios.
*/
-- OS EXERCICIOS 8, 9 E 10 ESTÃO NESSE ÚNICO ARQUIVO
DROP TABLE FORNECEDOR_PROCEDURE_2;
CREATE TABLE FORNECEDOR_PROCEDURE_2 (
    ID_FORNECEDOR NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    ENDERECO VARCHAR2(100),
    VALOR_VENDAS NUMBER,
    VALOR_COMISSOES NUMBER,
    VALOR_JUROS NUMBER,
    VALOR_LUCRO NUMBER
);

INSERT INTO FORNECEDOR_PROCEDURE_2 (ID_FORNECEDOR, NOME, ENDERECO, VALOR_VENDAS, VALOR_COMISSOES, VALOR_JUROS, VALOR_LUCRO) --1
VALUES (1, 'Fornecedor 1', 'Endereço 1', 500, NULL, NULL, NULL);
INSERT INTO FORNECEDOR_PROCEDURE_2 (ID_FORNECEDOR, NOME, ENDERECO, VALOR_VENDAS, VALOR_COMISSOES, VALOR_JUROS, VALOR_LUCRO) --2
VALUES (2, 'Fornecedor 2', 'Endereço 2', 600, NULL, NULL, NULL);
INSERT INTO FORNECEDOR_PROCEDURE_2 (ID_FORNECEDOR, NOME, ENDERECO, VALOR_VENDAS, VALOR_COMISSOES, VALOR_JUROS, VALOR_LUCRO) --3
VALUES (3, 'Fornecedor 3', 'Endereço 3', 350, NULL, NULL, NULL);
INSERT INTO FORNECEDOR_PROCEDURE_2 (ID_FORNECEDOR, NOME, ENDERECO, VALOR_VENDAS, VALOR_COMISSOES, VALOR_JUROS, VALOR_LUCRO) --4
VALUES (4, 'Fornecedor 4', 'Endereço 4', 750, NULL, NULL, NULL);
INSERT INTO FORNECEDOR_PROCEDURE_2 (ID_FORNECEDOR, NOME, ENDERECO, VALOR_VENDAS, VALOR_COMISSOES, VALOR_JUROS, VALOR_LUCRO) --5
VALUES (5, 'Fornecedor 5', 'Endereço 5', 420, NULL, NULL, NULL);

SELECT * FROM FORNECEDOR_PROCEDURE_2;

SET SERVEROUTPUT ON;

CREATE OR REPLACE PACKAGE PACKAGE_FORNECEDOR_PROCEDURE AS
    PROCEDURE CALCULAR_COMISSAO(ID_FORNECEDOR IN NUMBER);
    PROCEDURE CALCULAR_JUROS(ID_FORNECEDOR IN NUMBER);
    PROCEDURE CALCULAR_LUCRO(ID_FORNECEDOR IN NUMBER);
END PACKAGE_FORNECEDOR_PROCEDURE;
/

CREATE OR REPLACE PACKAGE BODY PACKAGE_FORNECEDOR_PROCEDURE AS
-- EXERCICIO 8
    PROCEDURE CALCULAR_COMISSAO(ID_FORNECEDOR IN NUMBER) AS
        V_VALOR_VENDAS FORNECEDOR_PROCEDURE_2.VALOR_VENDAS%TYPE;
        V_COMISSAO FORNECEDOR_PROCEDURE_2.VALOR_COMISSOES%TYPE;
    BEGIN
        SELECT VALOR_VENDAS 
        INTO V_VALOR_VENDAS 
        FROM FORNECEDOR_PROCEDURE_2 
        WHERE ID_FORNECEDOR = CALCULAR_COMISSAO.ID_FORNECEDOR;

        IF V_VALOR_VENDAS IS NULL THEN
            DBMS_OUTPUT.PUT_LINE('FORNECEDOR DE ID ' || ID_FORNECEDOR || ' NÃO ENCONTRADO');
        ELSE
            IF V_VALOR_VENDAS > 600 THEN
                V_COMISSAO := V_VALOR_VENDAS * 0.15;
            ELSE
                V_COMISSAO := V_VALOR_VENDAS * 0.05;
            END IF;

            UPDATE FORNECEDOR_PROCEDURE_2 
            SET VALOR_COMISSOES = V_COMISSAO 
            WHERE ID_FORNECEDOR = CALCULAR_COMISSAO.ID_FORNECEDOR;

            DBMS_OUTPUT.PUT_LINE('Comissão para o fornecedor de ID ' || ID_FORNECEDOR || ' foi calculada.');
        END IF;
    END CALCULAR_COMISSAO;
--EXERCICIO 9
    PROCEDURE CALCULAR_JUROS(ID_FORNECEDOR IN NUMBER) AS
        V_VALOR_VENDAS FORNECEDOR_PROCEDURE_2.VALOR_VENDAS%TYPE;
        V_JUROS FORNECEDOR_PROCEDURE_2.VALOR_JUROS%TYPE;
    BEGIN
        SELECT VALOR_VENDAS 
        INTO V_VALOR_VENDAS 
        FROM FORNECEDOR_PROCEDURE_2 
        WHERE ID_FORNECEDOR = CALCULAR_JUROS.ID_FORNECEDOR;

        IF V_VALOR_VENDAS IS NULL THEN
            DBMS_OUTPUT.PUT_LINE('FORNECEDOR DE ID ' || ID_FORNECEDOR || ' NÃO ENCONTRADO');
        ELSE
            V_JUROS := V_VALOR_VENDAS * 0.01;
            
            UPDATE FORNECEDOR_PROCEDURE_2 
            SET VALOR_JUROS = V_JUROS 
            WHERE ID_FORNECEDOR = CALCULAR_JUROS.ID_FORNECEDOR;

            DBMS_OUTPUT.PUT_LINE('Juros para o fornecedor de ID ' || ID_FORNECEDOR || ' foram calculados.');
        END IF;
    END CALCULAR_JUROS;
--EXERCICIO 10
    PROCEDURE CALCULAR_LUCRO(ID_FORNECEDOR IN NUMBER) AS
        V_VALOR_VENDAS FORNECEDOR_PROCEDURE_2.VALOR_VENDAS%TYPE;
        V_COMISSAO FORNECEDOR_PROCEDURE_2.VALOR_COMISSOES%TYPE;
        V_LUCRO FORNECEDOR_PROCEDURE_2.VALOR_LUCRO%TYPE;
    BEGIN
        SELECT VALOR_VENDAS, VALOR_COMISSOES 
        INTO V_VALOR_VENDAS, V_COMISSAO 
        FROM FORNECEDOR_PROCEDURE_2 
        WHERE ID_FORNECEDOR = CALCULAR_LUCRO.ID_FORNECEDOR;

        IF V_VALOR_VENDAS IS NULL THEN
            DBMS_OUTPUT.PUT_LINE('FORNECEDOR DE ID ' || ID_FORNECEDOR || ' NÃO ENCONTRADO');
        ELSE
            V_LUCRO := V_VALOR_VENDAS - V_COMISSAO;
            
            UPDATE FORNECEDOR_PROCEDURE_2 
            SET VALOR_LUCRO = V_LUCRO 
            WHERE ID_FORNECEDOR = CALCULAR_LUCRO.ID_FORNECEDOR;

            DBMS_OUTPUT.PUT_LINE('Lucro para o fornecedor de ID ' || ID_FORNECEDOR || ' foi calculado.');
        END IF;
    END CALCULAR_LUCRO;
END PACKAGE_FORNECEDOR_PROCEDURE;
/
-- AQUI (PROFESSOR) VOCÊ PODER ALTERAR O ID DOS FORNECEDORES PARA FAZER OS CALCULOS, O 1 E O 2 JA ESTAO ATUALIZADOS
BEGIN
    PACKAGE_FORNECEDOR_PROCEDURE.CALCULAR_COMISSAO(1);
    PACKAGE_FORNECEDOR_PROCEDURE.CALCULAR_JUROS(1);
    PACKAGE_FORNECEDOR_PROCEDURE.CALCULAR_LUCRO(1);
END;
/
