/*7) Criar uma FUNCTION PARA CALCULAR O VALOR DAS
PARCELAS DE UMA COMPRA DE UM CARRO, NAS SEGUINTES
CONDIÇÕES:
a) Parcelas para aquisição em 10 pagamentos.
b) O valor da compra deverá ser informado no parâmetro.
Publico
c) O valor total dos juros deverá ser aplicado sobre o montante
financiado, e deverá ser informado no parâmetro.
d) No final retornar o valor de cada parcela*/
SET SERVEROUTPUT ON;

CREATE OR REPLACE FUNCTION CALCULAR_PARCELAS_CARRO (
    VALOR_COMPRA IN NUMBER,
    TAXA_JUROS IN NUMBER
) RETURN NUMBER
IS
    NUM_PARCELAS CONSTANT NUMBER := 48; -- NÚMERO PARCELAS / COLOQUEI COMO SE FOSSEM 4 ANOS 
    VALOR_PARCELA NUMBER; -- VALOR DAS PARCELAS
    MONTANTE_FINANCIADO NUMBER; -- VALOR FINANCIADO
    JUROS_TOTAL NUMBER; -- VALOR TOTAL COM JUROS
BEGIN
    -- CALCULAR O MONTANTE FINANCIADO
    MONTANTE_FINANCIADO := VALOR_COMPRA * (1 + TAXA_JUROS / 100);
    
    -- CALCULAR O TOTAL DOS JUROS
    JUROS_TOTAL := MONTANTE_FINANCIADO - VALOR_COMPRA;
    
    -- CALCULAR O VALOR DE CADA PARCELA
    VALOR_PARCELA := MONTANTE_FINANCIADO / NUM_PARCELAS;
    
    -- EXIBIR AS INFORMAÇÕES NO DBMS_OUTPUT
    DBMS_OUTPUT.PUT_LINE('O valor do carro é de ' || TO_CHAR(VALOR_COMPRA, '99999.99'));
    DBMS_OUTPUT.PUT_LINE('O valor dos juros é de ' || TO_CHAR(JUROS_TOTAL, '99999.99'));
    
    RETURN VALOR_PARCELA;
END;
/

-- VALOR DA COMPRA / TAXA DE JUROS
SELECT CALCULAR_PARCELAS_CARRO(60000, 50) AS VALOR_PARCELA FROM DUAL;