/*criar um record para armazenar informações de um funcionário (id, nome, 
cargo, salario) da tabela funcionarios. Em seguida, insira valores no record.*/

CREATE TABLE collections_funcionarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,  -- ID auto incrementável
    nome VARCHAR2(100),                          -- Nome do funcionário
    cargo VARCHAR2(50),                          -- Cargo do funcionário
    salario NUMBER(10, 2),                       -- Salário do funcionário
    CONSTRAINT pk_funcionario_id PRIMARY KEY (id) -- Chave primária
);

SET SERVEROUTPUT ON;

DECLARE
  -- Definição do record para armazenar os dados de um funcionário
  TYPE funcionario_record IS RECORD (
    id      collections_funcionarios.id%TYPE,
    nome    collections_funcionarios.nome%TYPE,
    cargo   collections_funcionarios.cargo%TYPE,
    salario collections_funcionarios.salario%TYPE
  );

  -- Declaração de uma variável do tipo funcionario_record
  v_funcionario funcionario_record;

BEGIN
  -- Inserção de valores no record
  v_funcionario.id := 101;
  v_funcionario.nome := 'João Silva';
  v_funcionario.cargo := 'Desenvolvedor';
  v_funcionario.salario := 5000;

  -- Exibindo os valores armazenados no record
  DBMS_OUTPUT.PUT_LINE('ID: ' || v_funcionario.id);
  DBMS_OUTPUT.PUT_LINE('Nome: ' || v_funcionario.nome);
  DBMS_OUTPUT.PUT_LINE('Cargo: ' || v_funcionario.cargo);
  DBMS_OUTPUT.PUT_LINE('Salário: ' || v_funcionario.salario);

END;
/
