/* crie uma função que recebe o ID do cliente e retorna um record
com os dados do cliente(ID, nome e telefone)*/

CREATE TABLE collections_cliente (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID auto-incrementável
    nome VARCHAR2(100),  -- Nome do cliente
    telefone VARCHAR2(20)  -- Telefone do cliente
);

INSERT INTO collections_cliente (nome, telefone) VALUES ('João Silva', '1234-5678');
INSERT INTO collections_cliente (nome, telefone) VALUES ('Maria Oliveira', '9876-5432');
INSERT INTO collections_cliente (nome, telefone) VALUES ('Carlos Santos', '5555-5555');
COMMIT;


SET SERVEROUTPUT ON;

CREATE OR REPLACE FUNCTION get_cliente_info (p_id NUMBER)
RETURN collections_cliente%ROWTYPE
IS
  -- Declaração do record que armazenará os dados do cliente
  v_cliente collections_cliente%ROWTYPE;
BEGIN
  -- Consulta para buscar os dados do cliente
  SELECT *
  INTO v_cliente
  FROM collections_cliente
  WHERE id = p_id;
  
  -- Retornar o record com os dados do cliente
  RETURN v_cliente;
EXCEPTION
  -- Tratamento para caso o ID do cliente não seja encontrado
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Cliente não encontrado');
    RETURN NULL;
END;
/






